version: '3.8'

services:
  group1_web:
    image: php:8.1-apache
    container_name: group1_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - group1_db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  group1_db:
    image: mysql:8.0
    container_name: group1_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: group1_healthrwanda_db
      MYSQL_USER: healthuser
      MYSQL_PASSWORD: healthpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  group1_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: group1_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: group1_db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - group1_db

volumes:
  db_data:
